In [46]:
import numpy as np

In [47]:
np

<module 'numpy' from 'd:\\MACHINE\\machine-learning-zoomcamp-2026\\zoomcamp\\Lib\\site-packages\\numpy\\__init__.py'>

## Array

In [48]:
# create an array of zeros
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
# create an array of ones
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [50]:
# create an array with given input
np.full(10, 6.7)

array([6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7])

In [51]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [52]:
print(a[2])

3


In [53]:
# range 0 - infinity
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
# range number - infinity
np.arange(6, 10)

array([6, 7, 8, 9])

In [55]:
# array (start, end, equally divided in parts)
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multidimensional Array

In [56]:
# rows - columns
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [57]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [58]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
n[0,1] = 20

In [60]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [61]:
n[0]

array([ 1, 20,  3])

In [62]:
n[:,2]

array([3, 6, 9])

## Randomly Generated Arrays

In [63]:
np.random.rand(5,2)

array([[0.20464863, 0.61927097],
       [0.29965467, 0.26682728],
       [0.62113383, 0.52914209],
       [0.13457995, 0.51357812],
       [0.18443987, 0.78533515]])

In [64]:
# fix seed
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [65]:
# fix seed
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [66]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [67]:
# fix seed
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

## Element Wise Operations

In [68]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [69]:
a + 1

array([1, 2, 3, 4, 5])

In [70]:
b = (10 + (a * 2)) ** 2 / 100

In [71]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [72]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [73]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [74]:
a / b

array([0.        , 0.69444444, 1.02040816, 1.171875  , 1.2345679 ])

## Comparision Operations

In [75]:
a

array([0, 1, 2, 3, 4])

In [76]:
a >= 2

array([False, False,  True,  True,  True])

In [77]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [78]:
a > b

array([False, False,  True,  True,  True])

In [79]:
a[a > b]

array([2, 3, 4])

## Summarizing Operations

In [80]:
a.min()

np.int64(0)

In [81]:
a.max()

np.int64(4)

In [82]:
a.sum()

np.int64(10)

In [83]:
a.mean()

np.float64(2.0)

In [84]:
a.std()

np.float64(1.4142135623730951)