In [55]:
import numpy as np

## Vector Operations

In [56]:
u = np.array(
    [2, 4, 5, 6]
)

In [57]:
# element wise operations
2 * u

array([ 4,  8, 10, 12])

In [58]:
v = np.array(
    [1, 0, 0, 2]
)

In [59]:
u + v

array([3, 4, 5, 8])

## Vector - Vector Multiplication (dot product)

u * v  
row wise elements will be multiplied  
then those will be added  

## Multiplication

In [60]:
u.shape[0]

4

In [61]:
v.shape[0]

4

In [62]:
u.dot(v)

np.int64(14)

In [63]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
        
    return result

In [64]:
vector_vector_multiplication(u, v)

np.float64(14.0)

## Matrix Vector Multiplication

u0 - row  
for each row of the matrix, multiply with the number in v  
u -> (3 x 4)  
v -> (4 x 1)  
  
4 = 4

In [65]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1],
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [66]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
        
    return result

In [67]:
U.dot(v)

array([14,  5,  5])

In [68]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

## Matrix Matrix Multiplication

u -> (3 x 4)  
v -> (4 x 3)  

new matrix is created  
col u * v0  | u * v1 | u * v2  

In [69]:
V = np.array([
    [1,1,2],
    [0, 0.5, 1],
    [0,2,1],
    [2,1,0]
])

In [70]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
        
    return result

In [71]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [72]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity Matrix

diagonal is 1  
rest is 0  

U.I = U

In [73]:
I = np.eye(3)

In [74]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [75]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Matrix Inverse

A(inverse) * A = I  
only square matrix has an inverse